### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by Ergouzii** [lukePeavey/quota#2]
Hi, I discovered Quota today and it helped me with my project :)
But I found one typo in README.md. Under "usage", you have:
jQuery Example
```
  $.getJSON('https://quota.glitch.me/random'), function(data) {
    console.log(`${data.quoteText} -${data.quoteAuthor}`)
  }
```

There is one extra right parenthesis after `'https://quota.glitch.me/random'`
It should be: `$.getJSON('https://quota.glitch.me/random', function(data) {...`

**Comment by lukePeavey** [comment]
Im glad you were able to use quota in one of your projects!

Thanks for pointing this out. If you would like to fix it, you're welcome to submit a pull request. Otherwise I'll go ahead and fix. Thanks again

**Comment by Ergouzii** [comment]
Sure I will make a PR :)
